### PR TITLE
Add support for derivative

### PR DESCRIPTION
**Pull request by didrocks**
Enable Debian derivatives with Docker images and others to reuse travis.debian.net script.
Update the documentation and add 2 env variables to change container name and archive url.

### CODE REVIEW

**Comment by lamby** [comment]
Hey, thanks so much for the code! However, can you address the following this?

* Can we not autodetect the "derivative" in most cases?
* Can you also split the pocket into a separate PR?
* Also, "pocket" is not the right word in Debian - I had no idea what it was until I looked at the code. :p

**Comment by didrocks** [comment]
Hey Chris, thanks for the quick review!

> Can we not autodetect the "derivative" in most cases?

So, we can't autodetect it from the host, as Travis CI will mostly run an ubuntu machines.
We can hardcode a list of version names for derivatives and look in `debian/changelog` to detect from it. It will mean though updating the list everytime a new version for a derivative is coming up. Do you think that would be acceptable?
At least, what we can do (and which is less maintenance as shouldn't change often) is to update the archive url based on the selected derivative, so that the user doesn't have to set it.

Tell me what would be your preferred approach.

> Can you also split the pocket into a separate PR?
> Also, "pocket" is not the right word in Debian - I had no idea what it was until I looked at the code. :p

Oh correct, sorry, so used to that terminology, it's "component", isn't it? :)
Same than with the archive, we can file a "default" based on derivative name (Debian with only main, Ubuntu with main, restricted, universe, multiverse…). I'll so make this commit as a separate PR, but based on the new one with autodetection, wdyt?

**Comment by lamby** [comment]
> > Can we not autodetect the "derivative" in most cases?
>
> updating the list everytime a new version for a derivative is coming up

The worst case is Ubuntu which is only every 6 months. That is fine for me.

> Oh correct, sorry, so used to that terminology, it's "component", isn't it? :)

Yes.

>  I'll so make this commit as a separate PR, but based on the new one with autodetection, wdyt?

Please :)

**Comment by didrocks** [comment]
Ok, handling it! I'm pushing the COMPONENTS branch right now and will make the derivative based on it (as we'll pre-filled it). Will do a test run with one of my project before proposing this one.

**Comment by didrocks** [comment]
deprecating this branch for #56 (splitting the PR)

**Pull request closed without merging**
