### PR TITLE
Use a minimal docker image for autopkgtests

### PR DESCRIPTION
**Pull request by jamessan**
Since autopkgtest is using the null virtualization server (aka, the
existing environment), we don't want to re-use the build environment to
run the tests.  Not only does it have extra packages installed, but it
can break the "needs-recommends" Restriction.

Case in point, devscripts uses this Restriction, but since devscripts is
installed in the build environment (using --no-install-recommends) its
autopkgtests fail due to missing packages.

### CODE REVIEW

**Comment by jamessan** [comment]
I haven't verified this works correctly yet, since I'm not sure the best way to sanity check it other than convince you to merge it. :)

**Comment by lamby** [comment]
LGTM... Let's try it and see! I might rename ``.minimal`` to ``.autopkgtests``.

**Comment by jamessan** [comment]
> I might rename .minimal to .autopkgtests.

Makes sense.  That's more self-documenting. :)

Looks like it [worked](https://travis-ci.org/Debian/devscripts/jobs/274026912).

**Comment by lamby** [comment]
Renamed in https://github.com/lamby/travis.debian.net/commit/4d3afc34bc9262e2ee25c9a1235d698087d8ebc1

**Comment by lamby** [comment]
Thanks @jamessan

**Pull request merged**
