### PR TITLE
Set TRAVIS_DEBIAN_MIRROR to httpredir.debian.org.

### PR DESCRIPTION
**Pull request by stefanjenkner**

### CODE REVIEW

**Comment by lamby** [comment]
Hey,

Thanks for the PR! I would dearly love to use `httpredir.debian.org`, but take a look at:

 98e3a9a1d6b42339d8d3dd9467af727b3bc51a9e

I've been finding it unreliable other contexts too, but it had been especially flaky under travis-ci.org for whatever reason and, obviously, non-determinstically failing builds really really suck. Hence I won't be able to accept this change, sorry.

/@lamby

**Comment by szepeviktor** [comment]
@lamby Please update the HTML

``` html
        Which Debian mirror to use. By default, the
        <a href="http://httpredir.debian.org/">httpredir.debian.org</a>
        redirection service is used.
```

"Travis's machines are in Germany...."

**Comment by lamby** [comment]
Are they? :)

**Comment by szepeviktor** [comment]
https://blog.travis-ci.com/2013-blue-box-powers-travis-ci-infrastructure/
And Bluebox had US and European data centers.

**Comment by lamby** [comment]
Neat. I've updated the docs anyway - thanks :)

**Pull request closed without merging**
